generatorName: typescript-angular
gitUserId: x-atlas-consortia
gitRepoId: hra-api
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-angular.md
additionalProperties:
  npmName: '@hra-api/ng-client'
  npmVersion: 0.19.0
  licenseName: MIT
  apiModulePrefix: Hra
  configurationPrefix: HraApi
  fileNaming: kebab-case
  ngVersion: '20.0.0'
  queryParamObjectFormat: json
  stringEnums: true
  supportsES6: true
  useSingleRequestParameter: true
