generatorName: javascript
gitUserId: x-atlas-consortia
gitRepoId: hra-api
templateDir: openapi-clients/templates/javascript-client
# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/javascript.md
additionalProperties:
  projectName: '@hra-api/js-client'
  projectVersion: 0.19.0
  projectDescription: 'DEPRECATED: JavaScript client library for the HRA API'
  licenseName: MIT
  useES6: true
  usePromises: true
